### ISSUE TITLE
Suggestion: Add option to use spaces only after non-whitespace

### ISSUE THREAD

**Issue by Alhadis** [surdu/smart-indent#1]
[That's how I do it](https://github.com/Alhadis/Coding-Style). 😉

**Comment by surdu** [comment]
First, thanks for being such an early user of this package 😃 

Second, I'm afraid I don't understand what you mean 😞 Could you please elaborate ?

**Comment by Alhadis** [comment]
Oh, I admit I didn't install. But the "smart-tab" feature has been implemented by numerous packages before. I see now yours is only indenting on newlines, instead of when pressing <kbd>Tab</kbd>.

Basically, I was referring to stuff like this:

~~~js
»   let firstValue = 1;
»   let second ⎸
~~~

If I were to press <kbd>Tab</kbd>, I'd end up with:

~~~js
»   let firstValue = 1;
»   let second »   ⎸
~~~

But I'd really like it to do this:

~~~js
»   let firstValue = 1;
»   let second·····⎸
~~~

Whilst allowing me to still indent with tabs normally.

The difference in whether <kbd>Tab</kbd> indents with tabs or spaces depends on whether there's a non-whitespace character before the cursor.

**Comment by surdu** [comment]
Ah, now I get it, thanks!

Yeah, implementing the alignment like that would depend from language to language. Food for thought 😃 

Other than [atom-smart-tabs](https://atom.io/packages/atom-smart-tabs), do you know any other packages that help with alignment ?

**Comment by Alhadis** [comment]
None which I know off the top of my head. I've simply gotten by by holding the space-bar and letting a spastically-fast keyboard-repeat rate propel the editor's cursor across the page. 😉

Anyway, good luck!
